# Generated by Django 5.0.7 on 2025-12-02 01:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_preference', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('none', 'None')], default='email', max_length=10)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('standard_duration_days', models.PositiveSmallIntegerField(default=3, help_text='Standard number of days for task completion.')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
            ],
            options={
                'verbose_name': 'Task Definition',
                'verbose_name_plural': 'Task Definitions',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(auto_now=True)),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('on_time_tasks_count', models.PositiveIntegerField(default=0)),
                ('on_time_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttms_app.employee')),
            ],
            options={
                'verbose_name': 'Performance Metric',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('required_due_date', models.DateTimeField(help_text='The ultimate deadline for all tasks within this assignment.')),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('OT', 'On Time Completed'), ('L', 'Late Completed'), ('D', 'Overdue')], default='P', max_length=2)),
                ('task', models.ManyToManyField(related_name='assignments', to='ttms_app.task')),
                ('worker', models.ManyToManyField(related_name='assigned_tasks', to='ttms_app.employee')),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'ordering': ['required_due_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('WARN', 'Deadline Warning'), ('DUE', 'Deadline Today'), ('LATE', 'Overdue Notification'), ('CONF', 'Submission Confirmation')], max_length=4)),
                ('message', models.TextField()),
                ('trigger_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_datetime', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ttms_app.taskassignment')),
            ],
            options={
                'verbose_name': 'System Alert',
            },
        ),
    ]
